<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
        <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
        <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.10.1" />
        <PackageReference Include="Polly" Version="8.6.4" />
        <PackageReference Include="Polly.Extensions" Version="8.6.4" />
    </ItemGroup>

    <ItemGroup>
        <None Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest"/>
    </ItemGroup>
</Project>
